[workspace]
members = ["crates/tuple-projections", "crates/tuple-projections-derive"]
resolver = "3"

[workspace.package]
version = "0.1.2"
edition = "2024"
rust-version = "1.93"
repository = "https://github.com/alekseysidorov/tuple-projections"
license = "MIT OR Apache-2.0"

[workspace.metadata.crane]
name = "tuple-projections"

[workspace.dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "3.0", features = ["full"] }
include-utils = "0.2"
foundationdb-tuple = { version = "0.11", default-features = false }
tuple-projections-derive = { path = "crates/tuple-projections-derive", version = "0.1.2" }
trybuild = "1.0"

[workspace.lints.rust]
missing_docs = "warn"
unsafe_code = "deny"

[workspace.lints.rustdoc]
broken_intra_doc_links = "deny"

[workspace.lints.clippy]
pedantic = { level = "warn", priority = -1 }
module_name_repetitions = "allow"
